# Generated by Django 3.2.7 on 2021-10-05 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_messages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="title",
            new_name="topic",
        ),
        migrations.AlterField(
            model_name="messagestatus",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statuses",
                to="school_messages.message",
            ),
        ),
    ]
