# Generated by Django 3.2.7 on 2021-10-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_messages', '0002_auto_20211005_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagestatus',
            name='read_datetime',
        ),
    ]
