# Generated by Django 3.2.6 on 2021-08-15 13:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('classes', '0003_alter_class_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExactLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('exempt', 'Exempt'), ('excused', 'Excused'), ('none', 'None')], default='none', max_length=16)),
                ('exact_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.exactlesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('1', '7:00 - 7:45'), ('2', '7:50 - 8:35'), ('3', '8:45 - 9:30'), ('4', '9:40 - 10:25'), ('5', '10:45 - 11:30'), ('6', '11:40 - 12:25'), ('7', '12:35 - 13:20'), ('8', '13:30 - 14:15'), ('9', '14:25 - 15:10'), ('10', '15:20 - 16:05'), ('11', '16:15 - 17:00')], max_length=16)),
                ('weekday', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=16)),
                ('classroom', models.PositiveIntegerField()),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='classes.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='exactlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exact_lessons', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='exactlesson',
            name='presences',
            field=models.ManyToManyField(through='lessons.Presence', to='users.User'),
        ),
    ]
