# Generated by Django 3.2.5 on 2021-07-29 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_class_tutor'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('a', '7:00 - 7:45'), ('b', '7:50 - 8:35'), ('c', '8:45 - 9:30'), ('d', '9:40 - 10:25'), ('e', '10:45 - 11:30'), ('f', '11:40 - 12:25'), ('g', '12:35 - 13:20'), ('h', '13:30 - 14:15'), ('i', '14:25 - 15:10'), ('j', '15:20 - 16:05'), ('k', '16:15 - 17:00')], max_length=1)),
                ('weekday', models.CharField(choices=[('a', 'Monday'), ('b', 'Tuesday'), ('c', 'Wednesday'), ('d', 'Thursday'), ('e', 'Friday'), ('f', 'Saturday'), ('g', 'Sunday')], max_length=1)),
                ('classroom', models.PositiveIntegerField()),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='classes.class')),
                ('subject', models.ManyToManyField(related_name='lessons', to='lessons.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='users.user')),
            ],
        ),
    ]
