# Generated by Django 3.2.6 on 2021-08-11 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('lessons', '0002_auto_20210729_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExactLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=128)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.CharField(choices=[('1', '7:00 - 7:45'), ('2', '7:50 - 8:35'), ('3', '8:45 - 9:30'), ('4', '9:40 - 10:25'), ('5', '10:45 - 11:30'), ('6', '11:40 - 12:25'), ('7', '12:35 - 13:20'), ('8', '13:30 - 14:15'), ('9', '14:25 - 15:10'), ('10', '15:20 - 16:05'), ('11', '16:15 - 17:00')], max_length=16),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='weekday',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=16),
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('exempt', 'Exempt'), ('excused', 'Excused')], max_length=16)),
                ('exact_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.exactlesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='exactlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exact_lessons', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='exactlesson',
            name='presences',
            field=models.ManyToManyField(through='lessons.Presence', to='users.User'),
        ),
    ]
