# Generated by Django 3.2.7 on 2021-09-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_subject_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.CharField(choices=[('1', '7:00 - 7:45'), ('2', '7:50 - 8:35'), ('3', '8:45 - 9:30'), ('4', '9:40 - 10:25'), ('5', '10:45 - 11:30'), ('6', '11:40 - 12:25'), ('7', '12:35 - 13:20'), ('8', '13:30 - 14:15'), ('9', '14:25 - 15:10'), ('10', '15:20 - 16:05'), ('11', '16:15 - 17:00')], max_length=32),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='weekday',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=32),
        ),
    ]
