# Generated by Django 3.2.7 on 2021-09-29 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20210919_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lesson_files/')),
                ('lesson_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='lessons.lessonsession')),
            ],
        ),
    ]
