# Generated by Django 3.2.6 on 2021-08-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20210811_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('exempt', 'Exempt'), ('excused', 'Excused'), ('none', 'None')], default='none', max_length=16),
        ),
    ]
