# Generated by Django 3.2.7 on 2022-02-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_attachedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonsession',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
