# Generated by Django 3.2.7 on 2022-02-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_role"),
        ("lessons", "0005_alter_lessonsession_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Presence",
            new_name="Attendance",
        ),
        migrations.RemoveField(
            model_name="lessonsession",
            name="presences",
        ),
        migrations.AddField(
            model_name="lessonsession",
            name="attendances",
            field=models.ManyToManyField(through="lessons.Attendance", to="users.User"),
        ),
    ]
