# Generated by Django 3.2.7 on 2022-02-19 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0006_alter_class_tutor"),
        ("lessons", "0006_auto_20220215_1619"),
    ]

    operations = [
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "description",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("completion_date", models.DateTimeField()),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homeworks",
                        to="classes.class",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessons.subject",
                    ),
                ),
            ],
        ),
    ]
