# Generated by Django 3.2.7 on 2022-02-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0007_homework"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AttachedFile",
        ),
    ]
