# Generated by Django 3.2.7 on 2022-02-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0013_alter_homeworkrealisation_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="completion_date",
            field=models.DateField(),
        ),
    ]
