# Generated by Django 3.2.5 on 2021-07-28 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='tutor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
    ]
