# Generated by Django 3.2.6 on 2021-08-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='number',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
