# Generated by Django 3.2.6 on 2021-08-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_class_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='slug',
            field=models.SlugField(default='o', unique=True),
            preserve_default=False,
        ),
    ]
