# Generated by Django 3.2.7 on 2022-03-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0006_alter_class_tutor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="number",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
