# Generated by Django 3.2.5 on 2021-07-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=128)),
                ('building_number', models.CharField(max_length=16)),
                ('apartment_number', models.CharField(max_length=16, null=True)),
                ('city', models.CharField(max_length=128)),
                ('zip_code', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'addresses',
            },
        ),
    ]
