# Generated by Django 3.2.6 on 2021-08-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
