# Generated by Django 3.2.6 on 2021-08-22 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0005_alter_class_slug'),
        ('lessons', '0002_subject_slug'),
        ('users', '0004_alter_user_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_categories', to='classes.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_categories', to='lessons.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(choices=[(1.0, '1'), (1.5, '1+'), (1.75, '2-'), (2.0, '2'), (2.5, '2+'), (2.75, '3-'), (3.0, '3'), (3.5, '3+'), (3.75, '4-'), (4.0, '4'), (4.5, '4+'), (4.75, '5-'), (5.0, '5'), (5.5, '5+'), (5.75, '6-'), (6.0, '6')])),
                ('weight', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.gradecategory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_gotten', to='users.user')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='lessons.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_added', to='users.user')),
            ],
        ),
    ]
