# Generated by Django 3.2.6 on 2021-08-26 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_slug'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradecategory',
            options={'verbose_name_plural': 'grade categories'},
        ),
        migrations.AlterField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grades_added', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
