# Generated by Django 3.2.7 on 2022-02-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0002_auto_20210826_1146"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="seen_by_parent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="grade",
            name="seen_by_student",
            field=models.BooleanField(default=False),
        ),
    ]
