# Generated by Django 3.2.6 on 2021-08-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='radoslaw-cybulski', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
