# Generated by Django 3.2.7 on 2022-02-18 13:17

import django.db.models.deletion
from django.db import migrations, models

import django_school.apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_role"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django_school.apps.users.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="child",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent",
                to="users.user",
            ),
        ),
    ]
