# Generated by Django 3.2.7 on 2022-02-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="seen_by_parent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="note",
            name="seen_by_student",
            field=models.BooleanField(default=False),
        ),
    ]
